Nhom4_DoAnWeb_CHDT /Controllers/LoaiDTController.cs
using Nhom4_DoAnWeb_CHDT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class LoaiDTController : Controller
    {
        // GET: LoaiDT
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult danh_sach()
        {
            var all_LoaiDT = from lDT in data.tblLOAIDIENTHOAIs select lDT;
            return View(all_LoaiDT);
        }
        //Get: LoaiDT/Search

        public ActionResult tim_kiem(string searchName)
        {
            var search = data.tblLOAIDIENTHOAIs.Where(p => p.TENLOAI.ToLower().Contains(searchName.ToLower()));
            return View(search);
        }
        // GET: LoaiDT/Details/5
        public ActionResult thong_tin(int id)
        {
            var D_LoaiDT = data.tblLOAIDIENTHOAIs.First(p => p.MALOAI == id);
            if(D_LoaiDT != null)
                return View(D_LoaiDT);
            return HttpNotFound();
        }

        // GET: LoaiDT/Create
        public ActionResult them_moi()
        {
            return View();
        }

        // POST: LoaiDT/Create
        [HttpPost]
        public ActionResult them_moi(FormCollection collection, tblLOAIDIENTHOAI lDT)
        {
            try
            {
                // TODO: Add insert logic here
                var ten = collection["TENLOAI"];
                if (string.IsNullOrEmpty(ten))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.them_moi();
                }
                else
                {
                    lDT.TENLOAI = ten;
                    data.tblLOAIDIENTHOAIs.InsertOnSubmit(lDT);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: LoaiDT/Edit/5
        public ActionResult sua_thong_tin(int id)
        {
            var search = data.tblLOAIDIENTHOAIs.First(p => p.MALOAI == id);
            if(search != null)
                return View(search);
            return View("danh_sach");
        }

        // POST: LoaiDT/Edit/5
        [HttpPost]
        public ActionResult sua_thong_tin(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                var loaiDT = data.tblLOAIDIENTHOAIs.First(p => p.MALOAI == id);
                var tenloai = collection["TENLOAI"];
                if (string.IsNullOrEmpty(tenloai))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.sua_thong_tin(id);
                }
                else
                {
                    loaiDT.TENLOAI = tenloai;
                    UpdateModel(loaiDT);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: LoaiDT/Delete/5
        public ActionResult xoa_LoaiDT(int id)
        {
            var search = data.tblLOAIDIENTHOAIs.First(p => p.MALOAI == id);
            if (search != null)
                return View(search);
            return View("danh_sach");
        }

        // POST: LoaiDT/Delete/5
        [HttpPost]
        public ActionResult xoa_LoaiDT(int id, FormCollection collection)
        {
            var delLDT = data.tblLOAIDIENTHOAIs.First(p => p.MALOAI == id);
            data.tblLOAIDIENTHOAIs.DeleteOnSubmit(delLDT);
            data.SubmitChanges();
            return RedirectToAction("danh_sach");
        }
    }
}

Nhom4_DoAnWeb_CHDT /Views/LoaiDT/danh_sach.cshtml
@model IEnumerable<Nhom4_DoAnWeb_CHDT.Models.tblLOAIDIENTHOAI>
@{
    ViewBag.Title = "Danh sách Loại điện thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Danh Sách Loại Điện Thoại</h2>
<p>
    @Html.ActionLink("Thêm Loại Điện Thoại mới", "them_moi", null, new { @class = "btn btn-warning" })
</p>
@using (Html.BeginForm("tim_kiem", "LoaiDT", FormMethod.Get))
{
    <p>
        <input type="Text" class="form-control col-md-10 "name="searchName" placeholder="Nhập tên Loại Điện Thoại cần tìm">
        <input type="submit" value="Tìm kiếm" class="btn btn-info" />
    </p>
}
<table border="1px">
    <tr style="height:40px">
        <th width="100" style="text-align:center">Mã Loại ĐT</th>
        <th width="30%" style="text-align:center">Tên Loại ĐT</th>
        <th width="45%" style="text-align:center">Công cụ</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="height:40px">
            <td style="text-align:center">@item.MALOAI</td>
            <td style="text-align:center">@item.TENLOAI</td>
            <td style="text-align:center; font-size:20px">
                <a href="@Url.Action("sua_thong_tin", new { id = item.MALOAI })" title="Edit">
                    <img src="~/Content/images/edit-icon.png" alt="Edit" width="18px" />
                </a> |
                <a href="@Url.Action("thong_tin", new { id = item.MALOAI })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Edit" width="22px" />
                </a> |
                <a href="@Url.Action("xoa_LoaiDT", new { id = item.MALOAI })" title="Delete">
                    <img src="~/Content/images/delete-icon.png" alt="Edit" width="19px" />
                </a>
            </td>
        </tr>
    }
</table>
<style>
    a:hover img {
        position: relative;
        top: -3px;
    }

    img {
        vertical-align: text-bottom;
    }
</style>

Nhom4_DoAnWeb_CHDT /Views/LoaiDT/sua_thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblLOAIDIENTHOAI

@{
    ViewBag.Title = "Sửa thông tin Loại điện thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin Loại Điện Thoại</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MALOAI)
    <span style="color:red">@ViewData["Error"]</span>
    <div class="form-group">
        <p class="control-label col-md-2">Tên Loại</p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TENLOAI, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TENLOAI, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "danh_sach")
</div>

Nhom4_DoAnWeb_CHDT /Views/LoaiDT/them_moi.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblLOAIDIENTHOAI

@{
    ViewBag.Title = "Thêm mới Loại điện thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Thêm Loại Điện Thoại</h2>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <fieldset>
            <span style="color:red">@ViewData["Error"]</span>
            <div class="form-group">
                <label class="control-label col-md-2" for="TENLOAI">Tên Loại Điện Thoại:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="TENLOAI" name="TENLOAI" value="@ViewBag.TENLOAI" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm mới" class="btn btn-default" />
                </div>
            </div>
        </fieldset>
    </div>
}
<div>
     @Html.ActionLink("Quay lại", "danh_sach")
</div>

Nhom4_DoAnWeb_CHDT /Views/LoaiDT/thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblLOAIDIENTHOAI

@{
    ViewBag.Title = "Thông tin Loại điện thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông Tin Loại Điện Thoại</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã Loại: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MALOAI)
        </dd>
        <dt>
           Tên Loại: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENLOAI)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Quay lại", "danh_sach") | 
    @Html.ActionLink("Sửa", "sua_thong_tin", new { id = Model.MALOAI , @style = "margin-left:30px" })
</p>

Nhom4_DoAnWeb_CHDT /Views/LoaiDT/tim_kiem.cshtml
@model IEnumerable<Nhom4_DoAnWeb_CHDT.Models.tblLOAIDIENTHOAI>
@{
    ViewBag.Title = "Tìm kiếm Loại điện thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Loại Điện Thoại cần tìm</h2>
@using (Html.BeginForm("tim_kiem", "LoaiDT", FormMethod.Get))
{
    <p>
        <input type="Text" class="form-control col-md-10 " name="searchName" placeholder="Nhập tên Loại Điện Thoại cần tìm">
        <input type="submit" value="Tìm kiếm" class="btn btn-info" />
    </p>
}
<table border="1px">
    <tr>
        <th width="100" style="text-align:center">Mã Loại ĐT</th>
        <th width="30%" style="text-align:center">Tên Loại ĐT</th>
        <th width="45%"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align:center">@item.MALOAI</td>
            <td style="text-align:center">@item.TENLOAI</td>
            <td style="text-align:center">
                <a href="@Url.Action("sua_thong_tin", new { id = item.MALOAI })" title="Edit">
                    <img src="~/Content/images/edit-icon.png" alt="Edit" width="20px" />
                </a> |
                <a href="@Url.Action("thong_tin", new { id = item.MALOAI })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Edit" width="24px" />
                </a> |
                <a href="@Url.Action("xoa_LoaiDT", new { id = item.MALOAI })" title="Delete">
                    <img src="~/Content/images/delete-icon.png" alt="Edit" width="21px" />
                </a>
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Quay lại", "danh_sach")

Nhom4_DoAnWeb_CHDT /Views/LoaiDT/xoa_LoaiDT.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblLOAIDIENTHOAI

@{
    ViewBag.Title = "Xóa Loại điện thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Xóa Loại Điện Thoại</h2>

<h3>Chắc chắn muốn xóa Loại Điện Thoại này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Loại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENLOAI)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="submit" value="Xóa" class="btn btn-default" style="margin:10px 20px"/>
    }
</div>

<div>
    @Html.ActionLink("Quay lại", "danh_sach")
</div>