Nhom4_DoAnWeb_CHDT /Controllers/KhachHangController.cs
using Nhom4_DoAnWeb_CHDT.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class KhachHangController : Controller
    {
        // GET: KhachHang
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult danh_sach(int? page)
        {
            if (page == null) page = 1;
            int pageSize = 12;
            int pageNum = page ?? 1;
            var all_KH = from kh in data.tblKHACHHANGs select kh;
            return View(all_KH.ToPagedList(pageNum, pageSize));
        }
        public ActionResult danh_sach_QT(int? page)
        {
            if (page == null) page = 1;
            int pageSize = 12;
            int pageNum = page ?? 1;
            var all_KH = from kh in data.tblKHACHHANGs select kh;
            return View(all_KH.ToPagedList(pageNum, pageSize));
        }
        //Get: KhachHang/Search
        public ActionResult tim_kiem(string searchName)
        {
            var search = data.tblKHACHHANGs.Where(p => p.TENKH.ToLower().Contains(searchName.ToLower()));
            return View(search);
        }
        // GET: KhachHang/Details/5
        public ActionResult thong_tin(int id)
        {
            var D_kh = data.tblKHACHHANGs.First(p => p.MAKH == id);
            if (D_kh != null)
                return View(D_kh);
            return View("danh_sach");
        }

        // GET: KhachHang/Create
        public ActionResult them_moi()
        {
            return View();
        }

        // POST: KhachHang/Create
        [HttpPost]
        public ActionResult them_moi(FormCollection collection, tblKHACHHANG kh)
        {
            try
            {
                // TODO: Add insert logic here
                var C_tenKH = collection["TENKH"];
                var C_diachi = collection["DIACHI"];
                var C_dienthoai = collection["DIENTHOAI"];
                var C_email = collection["EMAIL"];
                var find = data.tblKHACHHANGs.FirstOrDefault(p => p.TENKH == C_tenKH && p.DIENTHOAI == C_dienthoai && p.EMAIL == C_email);
                if (!Regex.IsMatch(C_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.them_moi();
                }
                if (!Regex.IsMatch(C_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.them_moi();
                }
                if (string.IsNullOrEmpty(C_tenKH) || string.IsNullOrEmpty(C_diachi)
                    || string.IsNullOrEmpty(C_dienthoai) || string.IsNullOrEmpty(C_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.them_moi();
                }
                else
                {
                    if(find == null)
                    {
                        kh.TENKH = C_tenKH;
                        kh.DIACHI = C_diachi;
                        kh.DIENTHOAI = C_dienthoai;
                        kh.EMAIL = C_email;

                        data.tblKHACHHANGs.InsertOnSubmit(kh);
                        data.SubmitChanges();
                    }
                    else
                    {
                        return View("thong_tin",find);
                    }
                    return RedirectToAction("danh_sach");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: KhachHang/Edit/5
        public ActionResult sua_thong_tin(int? id)
        {
            var E_kh = data.tblKHACHHANGs.First(p => p.MAKH == id);
            if (E_kh != null)
                return View(E_kh);
            return View("danh_sach");
        }

        // POST: KhachHang/Edit/5
        [HttpPost]
        public ActionResult sua_thong_tin(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                var E_tenKH = collection["TENKH"];
                var E_diachi = collection["DIACHI"];
                var E_dienthoai = collection["DIENTHOAI"];
                var E_email = collection["EMAIL"];
                var kh = data.tblKHACHHANGs.First(p => p.MAKH == id);
                if (!Regex.IsMatch(E_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.sua_thong_tin(id);
                }
                if (!Regex.IsMatch(E_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.sua_thong_tin(id);
                }
                if (string.IsNullOrEmpty(E_tenKH) || string.IsNullOrEmpty(E_diachi)
                    || string.IsNullOrEmpty(E_dienthoai) || string.IsNullOrEmpty(E_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.sua_thong_tin(id);

                }
                else
                {
                    kh.TENKH = E_tenKH;
                    kh.DIACHI = E_diachi;
                    kh.DIENTHOAI = E_dienthoai;
                    kh.EMAIL = E_email;

                    UpdateModel(kh);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: KhachHang/Delete/5
        public ActionResult xoa_KH(int? id)
        {
            var D_kh = data.tblKHACHHANGs.First(p => p.MAKH == id);
            if (D_kh != null)
                return View(D_kh);
            return View("danh_sach");
        }

        // POST: KhachHang/Delete/5
        [HttpPost]
        public ActionResult xoa_KH(int id, FormCollection collection)
        {
            var delKH = data.tblKHACHHANGs.First(p => p.MAKH == id);
            data.tblKHACHHANGs.DeleteOnSubmit(delKH);
            data.SubmitChanges();
            return RedirectToAction("danh_sach");
        }
    }
}

Nhom4_DoAnWeb_CHDT /Views/KhachHang/danh_sach.cshtml
@model PagedList.IPagedList<Nhom4_DoAnWeb_CHDT.Models.tblKHACHHANG>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh sách Khách Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using Nhom4_DoAnWeb_CHDT.Models
@{ 
    tblTAIKHOAN tk = (tblTAIKHOAN)Session["TaiKhoan"];
}
<h2>Danh Sách Khách Hàng</h2>
<p>
    @Html.ActionLink("Thêm Khách Hàng mới", "them_moi", null, new { @class = "btn btn-warning" })
</p>
@using (Html.BeginForm("tim_kiem", "KhachHang", FormMethod.Get))
{
    <p>
        <input type="Text" class="form-control col-md-10 " name="searchName" placeholder="Nhập tên Khách Hàng cần tìm">
        <input type="submit" value="Search" class="btn btn-info" />
    </p>
}
<table border="1px">
    <tr>
        <th width="130" style="text-align:center">Mã Khách Hàng</th>
        <th width="150" style="text-align:center">Tên Khách Hàng</th>
        <th width="230" style="text-align:center">Địa chỉ</th>
        <th width="100" style="text-align:center">Điện Thoại</th>
        <th width="190" style="text-align:center">Email</th>
        <th width="160" style="text-align:center">Công cụ</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align:center">@item.MAKH</td>
            <td style="text-align:center">@item.TENKH</td>
            <td style="text-align:center">@item.DIACHI</td>
            <td style="text-align:center">@item.DIENTHOAI</td>
            <td style="text-align:center">@item.EMAIL</td>
            <td style="text-align:center; font-size:24px">
                <a href="@Url.Action("sua_thong_tin", new { id = item.MAKH })" title="Edit">
                    <img src="~/Content/images/edit-icon.png" alt="Edit" width="22px" />
                </a> |
                <a href="@Url.Action("thong_tin", new { id = item.MAKH })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Detail" width="29px" />
                </a>
                @if(tk.role == "QT")
                {
                    
                    <a href = "@Url.Action("xoa_KH", new { id = item.MAKH })" title = "Delete">
                      |  <img src="~/Content/images/delete-icon.png" alt = "Delete" width="25px"/>
                    </a >
                }
            </td>
        </tr>
    }
</table>
<div>
    <div>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) /  @Model.PageCount
    </div>
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("danh_sach", "KhachHang", new
   {
       page = page
   }))
    </div>
</div>
<style>
    a:hover img {
        position: relative;
        top: -3px;
    }

    img {
        vertical-align: text-bottom;
    }

    .MenuTrang li {
        display: inline;
    }
</style>
<style type="text/css">
    #mau-nut a {
        clear: both;
        background-color: orange;
        color: snow;
    }

        #mau-nut a:hover {
            background-color: darkcyan;
            color: snow;
        }
</style>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function () {
        var maxLength = 100;
        $(".show-read-more").each(function () {
            var myStr = $(this).text();
            if ($.trim(myStr).length > maxLength) {
                var newStr = myStr.substring(0, maxLength);
                var removedStr = myStr.substring(maxLength, $.trim(myStr).length);
                $(this).empty().html(newStr);

                $(this).append(' <a href="javascript:void(0);" class="read-more">đọc tiếp...</a>');

                $(this).append('<span class="more-text">' + removedStr + '</span>');
            }
        });
        $(".read-more").click(function () {
            $(this).siblings(".more-text").contents().unwrap();
            $(this).remove();
        });
    });
</script>
<style>
    .show-read-more .more-text {
        display: none;
    }
</style>

Nhom4_DoAnWeb_CHDT /Views/KhachHang/sua_thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblKHACHHANG

@{
    ViewBag.Title = "Sửa thông tin Khách Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin Khách Hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MAKH)
        <span style="color:red">@ViewData["Error"]</span>
        <div class="form-group">
            <p class="control-label col-md-2">Tên Khách Hàng: </p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Địa chỉ: </p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Điện thoại: </p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIENTHOAI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIENTHOAI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Email: </p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "danh_sach")
</div>

Nhom4_DoAnWeb_CHDT /Views/KhachHang/them_moi.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblKHACHHANG

@{
    ViewBag.Title = "Thêm mới Khách Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Thêm Khách Hàng</h2>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <fieldset>
            <span style="color:red">@ViewData["Error"]</span>
            <div class="form-group">
                <label class="control-label col-md-2" for="TENNV">Tên Khách Hàng:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="TENKH" name="TENKH" value="@ViewBag.TENKH" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="DIACHI">Địa chỉ:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="DIACHI" name="DIACHI" value="@ViewBag.DIACHI" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="DIENTHOAI">Điện thoại:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="DIENTHOAI" name="DIENTHOAI" value="@ViewBag.DIENTHOAI" />
                </div>
                <span style="color:red">@ViewData["SDTKhongHopLe"]</span>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="EMAIL">Email:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="EMAIL" name="EMAIL" value="@ViewBag.EMAIL" />
                </div>
                <span style="color:red">@ViewData["EmailKhongHopLe"]</span>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm mới" class="btn btn-default" />
                </div>
            </div>
        </fieldset>
    </div>
}
<div>
    @Html.ActionLink("Quay lại", "danh_sach")
</div>

Nhom4_DoAnWeb_CHDT /Views/KhachHang/thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblKHACHHANG

@{
    ViewBag.Title = "Thông tin Khách Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin Khách Hàng</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Khách Hàng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENKH)
        </dd>

        <dt>
            Địa chỉ:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            Điện Thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIENTHOAI)
        </dd>

        <dt>
            Email:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Quay lại", "danh_sach") |
    @Html.ActionLink("Sửa", "sua_thong_tin", new { id = Model.MAKH }) 
</p>

Nhom4_DoAnWeb_CHDT /Views/KhachHang/tim_kiem.cshtml
@model IEnumerable<Nhom4_DoAnWeb_CHDT.Models.tblKHACHHANG>
@{
    ViewBag.Title = "Tìm kiếm Khách Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Khách Hàng cần tìm</h2>
@using (Html.BeginForm("tim_kiem", "KhachHang", FormMethod.Get))
{
    <p>
        <input type="Text" class="form-control col-md-10 " name="searchName" placeholder="Nhập tên Khách Hàng cần tìm">
        <input type="submit" value="Search" class="btn btn-info" />
    </p>
}
@using Nhom4_DoAnWeb_CHDT.Models
@{ 
    tblTAIKHOAN tk = (tblTAIKHOAN)Session["TAIKHOAN"];
}
<table border="1px">
    <tr>
        <th width="130" style="text-align:center">Mã Khách Hàng</th>
        <th width="150" style="text-align:center">Tên Khách Hàng</th>
        <th width="230" style="text-align:center">Địa chỉ</th>
        <th width="100" style="text-align:center">Điện Thoại</th>
        <th width="190" style="text-align:center">Email</th>
        <th width="160"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align:center">@item.MAKH</td>
            <td style="text-align:center">@item.TENKH</td>
            <td style="text-align:center">@item.DIACHI</td>
            <td style="text-align:center">@item.DIENTHOAI</td>
            <td style="text-align:center">@item.EMAIL</td>
            <td style="text-align:center">
                <a href="@Url.Action("sua_thong_tin", new { id = item.MAKH })" title="Edit">
                    <img src="~/Content/images/edit-icon.png" alt="Edit" width="20px" />
                </a> |
                <a href="@Url.Action("thong_tin", new { id = item.MAKH })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Edit" width="24px" />
                </a>
                @if(tk.role == "QT")
                {
                    <a href="@Url.Action("xoa_KH", new { id = item.MAKH })" title="Delete">
                       | <img src="~/Content/images/delete-icon.png" alt="Edit" width="21px" />
                    </a>
                }
                
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Quay lại", "danh_sach")

Nhom4_DoAnWeb_CHDT /Views/KhachHang/xoa_KH.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblKHACHHANG

@{
    ViewBag.Title = "Xóa Khách Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Xóa Khách Hàng</h2>

<h3>Chắc chắn muốn xóa Khách Hàng này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Khách Hàng:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENKH)
        </dd>

        <dt>
            Địa chỉ:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            Điện thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIENTHOAI)
        </dd>

        <dt>
            Email:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "danh_sach")
        </div>
    }
</div>