Nhom4_DoAnWeb_CHDT /Controllers/HoaDonController.cs
using System;
using PagedList;
using Nhom4_DoAnWeb_CHDT.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;

namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class HoaDonController : Controller
    {
        // GET: HoaDon
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult nhap_TTHD()
        {
            return View();
        }
        [HttpPost]
        public ActionResult nhap_TTHD(FormCollection collection)
        {
            tblKHACHHANG kh = new tblKHACHHANG();
            tblTAIKHOAN tk = (tblTAIKHOAN)Session["TaiKhoan"];

            if(tk.role == "KH")
            { 
                var C_tenKH = collection["TENKH"];
                var C_diachi = collection["DIACHI"];
                var C_dienthoai = collection["DIENTHOAI"];
                var C_email = collection["EMAIL"];
                if (!Regex.IsMatch(C_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.nhap_TTHD();
                }
                if (!Regex.IsMatch(C_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.nhap_TTHD();
                }
                if (string.IsNullOrEmpty(C_tenKH) || string.IsNullOrEmpty(C_diachi)
                    || string.IsNullOrEmpty(C_dienthoai) || string.IsNullOrEmpty(C_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.nhap_TTHD();
                }
                else
                {
                    var find_KH = data.tblKHACHHANGs.FirstOrDefault(p => p.EMAIL == C_email && p.DIENTHOAI == C_dienthoai && p.DIACHI == C_diachi
                                                        && p.TENKH == C_tenKH);
                    if (find_KH != null)
                    {
                        Session["KhachHang"] = find_KH;
                        return RedirectToAction("danh_sach_HD");
                    }
                }
            }
            if (tk.role == "NV")
            {
                var C_tenNV = collection["TENNV"];
                var C_diachi = collection["DIACHI"];
                var C_dienthoai = collection["DIENTHOAI"];
                var C_email = collection["EMAIL"];
                if (!Regex.IsMatch(C_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.nhap_TTHD();
                }
                if (!Regex.IsMatch(C_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.nhap_TTHD();
                }
                if (string.IsNullOrEmpty(C_tenNV) || string.IsNullOrEmpty(C_diachi)
                    || string.IsNullOrEmpty(C_dienthoai) || string.IsNullOrEmpty(C_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.nhap_TTHD();
                }
                else
                {
                    var find_NV = data.tblNHANVIENs.FirstOrDefault(p => p.EMAIL == C_email && p.DIENTHOAI == C_dienthoai
                                                        && p.DIACHI == C_diachi && p.TENNV == C_tenNV);
                    if (find_NV != null)
                    {
                        Session["NhanVien"] = find_NV;
                        return RedirectToAction("danh_sach_HD");
                    }
                }
            }
            return View("trang_chu", "KhoaiTei");
        }
        public ActionResult danh_sach_HD(int? page)
        {
            if (page == null) page = 1;
            tblKHACHHANG kh = (tblKHACHHANG)Session["KhachHang"];
            if (kh != null)
            {
                var all_hd = (from s in data.tblHOADONs select s).Where(m => m.MAKH == kh.MAKH).OrderBy(m => m.MAHD);
                int pageSize = 12;
                int pageNum = page ?? 1;
                return View(all_hd.ToPagedList(pageNum, pageSize));
            }
            tblNHANVIEN nv = (tblNHANVIEN)Session["NhanVien"];
            if (nv != null)
            {
                var all_hd = (from s in data.tblHOADONs select s).Where(m => m.MANV == nv.MANV).OrderBy(m => m.MAHD);
                int pageSize = 12;
                int pageNum = page ?? 1;
                return View(all_hd.ToPagedList(pageNum, pageSize));
            }
            return View("trang_chu", "KhoaiTei");
        }
        public ActionResult danh_sach_HDQT(int? page)
        {
                var all_hd = (from s in data.tblHOADONs select s).OrderBy(m => m.MANV);
                int pageSize = 12;
                int pageNum = page ?? 1;
                return View(all_hd.ToPagedList(pageNum, pageSize));
        }
        // GET: HoaDon/Details/5
        public ActionResult thong_tin(int id)
        {
            var find = data.tblHOADONs.First(p => p.MAHD == id);
            if(find != null)
            {
                var cthd = data.tblCTHDs.Where(p => p.MAHD == id).ToList();
                ViewBag.cthd = cthd;
                return View(find);
            }
            return View("trang_chu", "KhoaiTei");
        }

        // GET: HoaDon/Create
        
        /*
        // GET: HoaDon/Delete/5
        public ActionResult xoa_HD(int id)
        {
            var find = data.tblHOADONs.FirstOrDefault(p => p.MAHD == id);
            if (find != null && find.NGAYLAP == DateTime.Now)
                return View(find);
            else
            {
                ViewData["thongbao"] = "Xin lỗi không thể xóa hóa đơn trong quá khứ";
                return this.xoa_HD(id);
            }
        }

        // POST: HoaDon/Delete/5
        [HttpPost]
        public ActionResult xoa_HD(int id, FormCollection collection)
        {
            var delHD = data.tblHOADONs.FirstOrDefault(p => p.MAHD == id);
            if(delHD != null)
            {
                var cthd = data.tblCTHDs.Where(p => p.MAHD == id).ToList();
                foreach (var item in cthd)
                {
                    var dt = data.tblDIENTHOAIs.FirstOrDefault(p => p.MADT == item.MADT);
                    if (dt != null)
                    {
                        dt.SLTON += item.SLMUA;
                    }
                }
                ViewBag.cthd = cthd;
                data.tblCTHDs.DeleteAllOnSubmit(cthd);
                data.SubmitChanges();
            }
            data.tblHOADONs.DeleteOnSubmit(delHD);
            data.SubmitChanges();
            return RedirectToAction("danh_sach_HDQTs");
        }
        */
        public ActionResult ThongKe()
        {
            var startDate = Convert.ToDateTime(Request.QueryString.Get("start-date"));
            var endDate = Convert.ToDateTime(Request.QueryString.Get("end-date"));
            var totalRevenue = data.tblHOADONs
                .Where(i => i.NGAYLAP >= startDate && i.NGAYLAP <= endDate)
                .Sum(i => i.TONGTG);
            ViewBag.TotalRevenue = totalRevenue;
            ViewBag.StartDate = startDate;
            ViewBag.EndDate = endDate;
            var hoadon = data.tblHOADONs.Where(i => i.NGAYLAP >= startDate && i.NGAYLAP <= endDate);
            return View(hoadon);
        }


    }
}

Nhom4_DoAnWeb_CHDT /Controllers/NCCController.cs
using Nhom4_DoAnWeb_CHDT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class NCCController : Controller
    {
        // GET: NCC
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult danh_sach()
        {
            var all_NCC = from ncc in data.tblNHACUNGCAPs select ncc;
            return View(all_NCC);
        }
        //Get: LoaiDT/Search
        public ActionResult tim_kiem(string searchName)
        {
            var search = data.tblNHACUNGCAPs.Where(p => p.TENNCC.ToLower().Contains(searchName.ToLower()));
            return View(search);
        }
        // GET: NCC/Details/5
        public ActionResult thong_tin(int id)
        {
            var D_nhacungcap = data.tblNHACUNGCAPs.First(m => m.MANCC == id);
            if(D_nhacungcap != null)
                return View(D_nhacungcap);
            return View("danh_sach");
        }
        // GET: NCC/Create
        public ActionResult them_moi()
        {
            return View();
        }
        
        // POST: NCC/Create
        [HttpPost]
        public ActionResult them_moi(FormCollection collection, tblNHACUNGCAP ncc)
        {
            try
            {
                var C_tenNCC = collection["TENNCC"];
                var C_diachi = collection["DIACHI"];
                var C_dienthoai = collection["DIENTHOAI"];
                var C_email = collection["EMAIL"];
                if (!Regex.IsMatch(C_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.them_moi();
                }
                if (!Regex.IsMatch(C_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.them_moi();
                }
                if (string.IsNullOrEmpty(C_tenNCC) || string.IsNullOrEmpty(C_diachi)
                    || string.IsNullOrEmpty(C_dienthoai) || string.IsNullOrEmpty(C_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.them_moi();
                }
                else
                {
                    ncc.TENNCC = C_tenNCC;
                    ncc.DIACHI = C_diachi;
                    ncc.DIENTHOAI = C_dienthoai;
                    ncc.EMAIL = C_email;

                    data.tblNHACUNGCAPs.InsertOnSubmit(ncc);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: NCC/Edit/5
        public ActionResult sua_thong_tin(int? id)
        {
            var ncc = data.tblNHACUNGCAPs.First(m => m.MANCC == id);
            if(ncc != null)
                return View(ncc);
            return View("danh_sach");
        }

        // POST: NCC/Edit/5
        [HttpPost]
        public ActionResult sua_thong_tin(int id, FormCollection collection)
        {
            try
            {
                var ncc = data.tblNHACUNGCAPs.First(p => p.MANCC == id);
                var E_tenncc = collection["TENNCC"];
                var E_diachi = collection["DIACHI"];
                var E_dienthoai = collection["DIENTHOAI"];
                var E_email = collection["EMAIL"];
                if (!Regex.IsMatch(E_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.them_moi();
                }
                if (!Regex.IsMatch(E_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.them_moi();
                }
                if (string.IsNullOrEmpty(E_tenncc) || string.IsNullOrEmpty(E_diachi)
                    || string.IsNullOrEmpty(E_dienthoai) || string.IsNullOrEmpty(E_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.sua_thong_tin(id);
                }
                else
                {
                    ncc.TENNCC = E_tenncc;
                    ncc.DIACHI = E_diachi;
                    ncc.DIENTHOAI = E_dienthoai;
                    ncc.EMAIL = E_email;

                    UpdateModel(ncc);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: NCC/Delete/5
        public ActionResult xoa_NCC(int? id)
        {
            var search = data.tblNHACUNGCAPs.First(p => p.MANCC == id);
            if (search != null)
                return View(search);
            return View("danh_sach");
        }

        // POST: NCC/Delete/5
        [HttpPost]
        public ActionResult xoa_NCC(int id, FormCollection collection)
        {
            var delNCC = data.tblNHACUNGCAPs.First(p => p.MANCC == id);
            data.tblNHACUNGCAPs.DeleteOnSubmit(delNCC);
            data.SubmitChanges();
            return RedirectToAction("danh_sach");
        }
    }
}

Nhom4_DoAnWeb_CHDT /Controllers/NhapKhoController.cs
using Nhom4_DoAnWeb_CHDT.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class NhapKhoController : Controller
    {
        // GET: NhapKho
        MyDataDataContext data = new MyDataDataContext();

        public ActionResult danh_sach_NK(int? page)
        {
            var all_nk = (from s in data.tblNHAPKHOs select s).OrderBy(m => m.MAPNK);
            int pageSize = 12;
            int pageNum = page ?? 1;
            return View(all_nk.ToPagedList(pageNum, pageSize));
        }
        // GET: NhapKho/Details/5
        public ActionResult thong_tin(int id)
        {
            var find = data.tblNHAPKHOs.First(p => p.MAPNK == id);
            if (find != null)
            {
                var ctnk = data.tblCTPNHAPKHOs.Where(p => p.MAPNK == id).ToList();
                ViewBag.cthd = ctnk;
                return View(find);
            }
            return View("Index", "Home");
        }

        public ActionResult xoa_NK(int id)
        {
            var find = data.tblNHAPKHOs.FirstOrDefault(p => p.MAPNK == id);
            if (find != null)
                return View(find);
            return View("Index", "Home");
        }

        // POST: HoaDon/Delete/5
        [HttpPost]
        public ActionResult xoa_NK(int id, FormCollection collection)
        {
            var delNK = data.tblNHAPKHOs.FirstOrDefault(p => p.MAPNK == id);
            if (delNK != null)
            {
                var ctnk = data.tblCTPNHAPKHOs.Where(p => p.MAPNK == id).ToList();
                foreach (var item in ctnk)
                {
                    var dt = data.tblDIENTHOAIs.FirstOrDefault(p => p.MADT == item.MADT);
                    if (dt != null)
                    {
                        dt.SLTON -= item.SL;
                    }
                }
                ViewBag.ctnk = ctnk;
                data.tblCTPNHAPKHOs.DeleteAllOnSubmit(ctnk);
                data.SubmitChanges();
            }
            data.tblNHAPKHOs.DeleteOnSubmit(delNK);
            data.SubmitChanges();
            return RedirectToAction("danh_sach");
        }
    }
}

Nhom4_DoAnWeb_CHDT /Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="header">
        <div class="logo">
            <a href="@Url.Action("trang_chu","KhoaiTei")">
                <img src="~/Content/images/logo_header.jpg" alt="">
            </a>
        </div>
        <div class="search-header">
            @using (Html.BeginForm("tim_kiem", "DienThoai", FormMethod.Get))
            {
                <p>
                    <input type="Text" class="form-control col-md-10 search__dt" name="searchName" placeholder="Nhập tên Điện Thoại cần tìm...">
                    <input type="submit" value="Search" class="btn btn-info" />
                </p>
            }
        </div>
    </div>
    @using Nhom4_DoAnWeb_CHDT.Models
    @{
        tblTAIKHOAN tk = (tblTAIKHOAN)Session["TaiKhoan"];
    }
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trang chủ", "trang_chu", "KhoaiTei")</li>
                    <li>@Html.ActionLink("Giới thiệu", "gioi_thieu", "KhoaiTei")</li>
                    <li>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                   role="button" aria-haspopup="true" aria-
                                   expanded="false">Điện thoại <span class="caret"></span></a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li> <a href="@Url.Action("DienThoai", "DienThoai", new{ maloai = 1})">Apple</a></li>
                                    <li> <a href="@Url.Action("DienThoai", "DienThoai", new{ maloai = 2})">SamSung</a></li>
                                    <li> <a href="@Url.Action("DienThoai", "DienThoai", new{ maloai = 3})">Oppo</a></li>
                                    <li> <a href="@Url.Action("DienThoai", "DienThoai", new{ maloai = 4})">Xiaomi</a></li>
                                    <li> <a href="@Url.Action("DienThoai", "DienThoai", new{ maloai = 6})">Realmi</a></li>
                                    <li> <a href="@Url.Action("DienThoai", "DienThoai", new{ maloai = 8})">Vivo</a></li>
                                    <li role="separator" class="divider"> </li>
                                    <li> <a href="@Url.Action("danh_sach", "DienThoai")">Danh Sách Điện thoại</a></li>
                                    @if (tk != null && tk.role == "QT")
                                    {
                                        <li role="separator" class="divider"> </li>
                                        <li> <a href="@Url.Action("danh_sach_QT", "DienThoai")">Quản lý Điện thoại</a></li>
                                    }
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Dịch vụ sửa chữa", "dich_vu_sua_chua", "KhoaiTei")</li>
                    <li>@Html.ActionLink("Giỏ hàng", "GioHang", "GioHang")</li>
                    @if (tk != null)
                    {
                        if (tk.role == "QT")
                        {
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                                       role="button" aria-haspopup="true" aria-
                                       expanded="false">Danh mục <span class="caret"></span></a>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <li>@Html.ActionLink("Khách hàng", "danh_sach", "KhachHang")</li>
                                        <li>@Html.ActionLink("Nhân viên", "danh_sach", "NhanVien")</li>
                                        <li>@Html.ActionLink("Nhà cung cấp", "danh_sach", "NCC")</li>
                                        <li>@Html.ActionLink("Nhập kho", "danh_sach_NK", "NhapKho")</li>
                                        <li>@Html.ActionLink("Hóa đơn", "danh_sach_HDQT", "HoaDon")</li>
                                        <li>@Html.ActionLink("Tài khoản", "danh_sach", "NguoiDung")</li>
                                        <li role="separator" class="divider"> </li>
                                        <li>@Html.ActionLink("Thống kê", "ThongKe", "HoaDon")</li>
                                    </ul>
                                </li>
                            </ul>
                        }
                        if (tk.role == "NV")
                        {
                            <li>@Html.ActionLink("Khách hàng", "danh_sach", "KhachHang")</li>
                        }
                        if (tk.role == "NV" || tk.role == "KH")
                        {
                            <li>@Html.ActionLink("Hóa đơn", "nhap_TTHD", "HoaDon")</li>
                        }
                        <li>
                            <a href="@Url.Action("DangXuat", "NguoiDung")">Đăng xuất</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("DangNhap", "NguoiDung")">Đăng nhập</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="footer">
            <div class="foot__menu">
                <div class="info">
                    <h3><span style="font-size:24px;">KhoaiTei Shop</span> (Uy tín tạo nên thương hiệu)</h3>
                    <p style="font-size:18px">
                        Chúng tôi tin vào dịch vụ của mình và bạn biết điều đó.
                    </p>
                    <a href="@Url.Action("trang_chu","KhoaiTei")">
                        <img src="~/Content/images/logo_footer.jpg" alt="" width="250px">
                    </a>
                </div>
                <div class="line"></div>
                <div class="support" style="font-size:18px">
                    <h5 style="font-size:24px">Bạn cần hỗ trợ</h5>
                    <p>Email: vinhtranthe117@gmail.com</p>
                    <p>Phone: 0935851107 </p>
                    @*  <p>Địa chỉ: 11/07 Biên Hoà, Đồng Nai</p>*@
                    <p><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d979.2362026355078!2d106.9117401614032!3d10.967538458599513!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174ddf600bf14c1%3A0x2e6781657d3a9c92!2zR2nDoW8geOG7qSBOZ-G7jWMgxJDhu5NuZyAtIEdpw6FvIEjhuqF0IEjDsmEgVGhhbmggLSBHacOhbyBwaOG6rW4gWHXDom4gTOG7mWM!5e0!3m2!1svi!2sus!4v1680445063434!5m2!1svi!2sus" width="94%" height="100" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></p>
                </div>
                <div class="line"></div>
                <div class="foot-menu" style="font-size:18px">
                    <h5 style="font-size:24px">Danh mục</h5>
                    <ul>
                        <li>
                            <a href="@Url.Action("trang_chu", "KhoaiTei")">Trang chủ</a>
                        </li>
                        <li>
                            <a href="@Url.Action("gioi_thieu", "KhoaiTei")">Giới thiệu</a>
                        </li>
                        <li>
                            <a href="@Url.Action("danh_sach", "DienThoai")">Sản phẩm</a>
                        </li>
                        <li>
                            <a href="@Url.Action("GioHang", "GioHang")">Đặt hàng</a>
                        </li>
                    </ul>
                </div>
                <div class="followus" style="font-size:18px">
                    <h5 style="font-size:24px">Mạng xã hội</h5>
                    <ul>
                        <li>
                            <a href="https://www.facebook.com/vin1107/">Facebook</a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/_trn.vinh/">Instagram</a>
                        </li>
                        <li>
                            <a href="https://www.tiktok.com/_trn.vinh">Tiktok</a>
                        </li>
                        <li>
                            <a href="https://mobile.twitter.com/vysky30">Twitter</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="line-end"></div>
            <div class="foot--end">
                <p>© 2023 - Designed by _trn.vinh</p>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("upload", required: false)
    @RenderSection("them_moi", required: false)
</body>

</html>