Nhom4_DoAnWeb_CHDT /Controllers/DienThoaiController.cs
using Nhom4_DoAnWeb_CHDT.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class DienThoaiController : Controller
    {
        // GET: DienThoai
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult danh_sach(int? page)
        {
            if (page == null) page = 1;
            var all_dt = (from s in data.tblDIENTHOAIs select s).Where(m => m.SLTON > 0).OrderBy(m => m.MALOAI);
            int pageSize = 12;
            int pageNum = page ?? 1;
            return View(all_dt.ToPagedList(pageNum, pageSize));
        }
        public ActionResult danh_sach_QT(int? page)
        {
            if (page == null) page = 1;
            var all_dt = (from s in data.tblDIENTHOAIs select s).Where(m => m.SLTON > 0).OrderBy(m => m.MALOAI);
            int pageSize = 8;
            int pageNum = page ?? 1;
            return View(all_dt.ToPagedList(pageNum, pageSize));
        }
        //Get: KhachHang/Search
        public ActionResult tim_kiem(string searchName, int? page)
        {
            if (page == null) page = 1;
            int pageSize = 12;
            int pageNum = page ?? 1;
            if (searchName == null)
                Session["searchDT"] = null;
            else
                Session["searchDT"] = searchName;
            var search = data.tblDIENTHOAIs.Where(p => p.TENDT.ToLower().Contains(searchName.ToLower()));
            return View(search.ToPagedList(pageNum, pageSize));
        }
        public ActionResult DienThoai(int? page, int maloai)
        {
            maloai = int.Parse(Request.QueryString["MALOAI"]);
            if (string.IsNullOrEmpty(maloai.ToString()))
            {
                maloai = 1;
            }
            if (page == null) page = 1;
            var all_dt = (from s in data.tblDIENTHOAIs select s).Where(m => m.SLTON > 0 && m.MALOAI == maloai);
            int pageSize = 8;
            int pageNum = page ?? 1;
            if (maloai == 1) ViewBag.Filter = "Apple";
            else if(maloai == 2) ViewBag.Filter = "SamSung";
            else if (maloai == 3) ViewBag.Filter = "Oppo";
            else if (maloai == 4) ViewBag.Filter = "Xiaomi";
            else if (maloai == 6) ViewBag.Filter = "Realmi";
            else if (maloai == 8) ViewBag.Filter = "Vivo";
            return View("DienThoai", all_dt.ToPagedList(pageNum, pageSize));

        }
        // GET: DienThoai/Details/5
        public ActionResult thong_tin(int id)
        {
            var D_dt = data.tblDIENTHOAIs.FirstOrDefault(p => p.MADT == id);
            if(D_dt != null)
                return View(D_dt);
            return View("danh_sach");
        }
        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
            return "/Content/images/" + file.FileName;
        }
        // GET: DienThoai/Create
        public ActionResult them_moi()
        {
            return View();
        }

        // POST: DienThoai/Create
        [HttpPost]
        public ActionResult them_moi(FormCollection collection, tblDIENTHOAI dt)
        {
            try
            {
                // TODO: Add insert logic here
                var C_tenDT = collection["TENDT"];
                var C_hinh = collection["HINH"];
                var C_giaMua = collection["GIAMUA"];
                var C_giaBan = collection["GIABAN"];
                var C_moTa = collection["MOTA"];
                var C_sLTon = collection["SLTON"];
                var C_maLoai = collection["MALOAI"];

                if (string.IsNullOrEmpty(C_maLoai) || string.IsNullOrEmpty(C_tenDT)
                    || string.IsNullOrEmpty(C_hinh) || string.IsNullOrEmpty(C_giaMua)
                    || string.IsNullOrEmpty(C_giaBan) || string.IsNullOrEmpty(C_moTa)
                    || string.IsNullOrEmpty(C_sLTon))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.them_moi();
                }
                else
                {
                    dt.MADT = int.Parse(data.tblDIENTHOAIs.Max(p => p.MADT).ToString()) + 1;
                    dt.TENDT = C_tenDT;
                    dt.HINH = C_hinh;
                    dt.GIAMUA = decimal.Parse(C_giaMua);
                    dt.GIABAN = decimal.Parse(C_giaBan);
                    dt.MOTA = C_moTa;
                    dt.SLTON = int.Parse(C_sLTon);
                    dt.MALOAI = int.Parse(C_maLoai);

                    data.tblDIENTHOAIs.InsertOnSubmit(dt);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach", "DienThoai");
                }
                return this.them_moi();
            }
            catch
            {
                return View();
            }
        }

        // GET: DienThoai/Edit/5
        public ActionResult sua_thong_tin(int? id)
        {
            var E_dt = data.tblDIENTHOAIs.FirstOrDefault(p => p.MADT == id);
            if(E_dt != null)
                return View(E_dt);
            return View("danh_sach");
        }

        // POST: DienThoai/Edit/5
        [HttpPost]
        public ActionResult sua_thong_tin(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                var C_maLoai = collection["MALOAI"];
                var C_tenDT = collection["TENDT"];
                var C_hinh = collection["HINH"];
                var C_giaMua = collection["GIAMUA"];
                var C_giaBan = collection["GIABAN"];
                var C_moTa = collection["MOTA"];
                var C_sLTon = collection["SLTON"];
                var dt = data.tblDIENTHOAIs.First(p => p.MADT == id);
                if (string.IsNullOrEmpty(C_maLoai) || string.IsNullOrEmpty(C_tenDT)
                    || string.IsNullOrEmpty(C_hinh) || string.IsNullOrEmpty(C_giaMua)
                    || string.IsNullOrEmpty(C_giaBan) || string.IsNullOrEmpty(C_moTa)
                    || string.IsNullOrEmpty(C_sLTon))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.sua_thong_tin(id);
                }
                else
                {
                    dt.MALOAI = int.Parse(C_maLoai);
                    dt.TENDT = C_tenDT;
                    dt.HINH = C_hinh;
                    dt.GIAMUA = decimal.Parse(C_giaMua);
                    dt.GIABAN = decimal.Parse(C_giaBan);
                    dt.MOTA = C_moTa;
                    dt.SLTON = int.Parse(C_sLTon);
                    UpdateModel(dt);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
                return this.sua_thong_tin(id);
            }
            catch
            {
                return View();
            }
        }

        // GET: DienThoai/Delete/5
        public ActionResult xoa_DT(int id)
        {
            var D_dt = data.tblDIENTHOAIs.FirstOrDefault(p => p.MADT == id);
            if(D_dt != null)
                return View(D_dt);
            return View("danh_sach");
        }

        // POST: DienThoai/Delete/5
        [HttpPost]
        public ActionResult xoa_DT(int id, FormCollection collection)
        {
            var delDT = data.tblDIENTHOAIs.First(p => p.MADT == id);
            data.tblDIENTHOAIs.DeleteOnSubmit(delDT);
            data.SubmitChanges();
            return RedirectToAction("danh_sach");
        }
        
    }
}

Nhom4_DoAnWeb_CHDT /Controllers/KhoaiTeiController.cs
using Nhom4_DoAnWeb_CHDT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class KhoaiTeiController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult trang_chu()
        {
            var all_sach = (from s in data.tblDIENTHOAIs select s).Where(m => m.SLTON > 0).OrderBy(m => m.MALOAI);
            return View(all_sach);
        }
        
        public ActionResult gioi_thieu()
        {
            return View();
        }

        public ActionResult dich_vu_sua_chua()
        {
            return View();
        }
        
    }
}

Nhom4_DoAnWeb_CHDT /Views/DienThoai/DienThoai.cshtml
@model PagedList.IPagedList<Nhom4_DoAnWeb_CHDT.Models.tblDIENTHOAI>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Danh sách điện thoại";
}
<h2>@ViewBag.Filter</h2>
<div class="row">
    @foreach (var item in Model)
    {
        var gia = item.GIABAN.ToString().Replace(",0000", "");
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-default">
                <div class="panel panel-heading">
                    <img src="@item.HINH" alt="hinh thumnail" width="214px" height="214px">
                </div>
                <div class="panel-body">
                    @item.TENDT
                    <p><strong>Giá: </strong>@gia</p>
                    <p><strong>Số lượng tồn: </strong>@item.SLTON</p>
                </div>
                <div class="panel-footer clearfix">
                    <div class="pull-right">
                        <a class="btn btn-success" href="@Url.Action("ThemGioHang", "Giohang",
                            new { @id = item.MADT, @strUrl = Request.Url.ToString() })">Đặt mua</a>
                    </div>
                    <div class="pull-left">
                        @Html.ActionLink("Thông tin", "thong_tin", "DienThoai", new { id = item.MADT }, new { @class = "btn btn-default" })
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div>
    <div>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) /  @Model.PageCount
    </div>
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("DienThoai", "DienThoai", new
        {
            page = page
        }))
    </div>
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>
<style type="text/css">
    #mau-nut a {
        clear: both;
        background-color: orange;
        color: snow;
    }

        #mau-nut a:hover {
            background-color: darkcyan;
            color: snow;
        }
</style>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function () {
        var maxLength = 100;
        $(".show-read-more").each(function () {
            var myStr = $(this).text();
            if ($.trim(myStr).length > maxLength) {
                var newStr = myStr.substring(0, maxLength);
                var removedStr = myStr.substring(maxLength, $.trim(myStr).length);
                $(this).empty().html(newStr);

                $(this).append(' <a href="javascript:void(0);" class="read-more">đọc tiếp...</a>');

                $(this).append('<span class="more-text">' + removedStr + '</span>');
            }
        });
        $(".read-more").click(function () {
            $(this).siblings(".more-text").contents().unwrap();
            $(this).remove();
        });
    });
</script>
<style>
    .show-read-more .more-text {
        display: none;
    }
</style>

Nhom4_DoAnWeb_CHDT /Views/DienThoai/danh_sach.cshtml
@model PagedList.IPagedList<Nhom4_DoAnWeb_CHDT.Models.tblDIENTHOAI>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Điện Thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Danh sách các Điện Thoại hiện có tại shop</h2>
<div class="row">
    @foreach (var item in Model)
    {
        var gia = item.GIABAN.ToString().Replace(",0000", "");
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-default">
                <div class="panel panel-heading">
                    <img src="@item.HINH" alt="hinh thumnail" width="214px" height="214px">
                </div>
                <div class="panel-body">
                    @item.TENDT
                    <p><strong>Giá: </strong>@gia</p>
                    <p><strong>Số lượng tồn: </strong>@item.SLTON</p>
                </div>
                <div class="panel-footer clearfix">
                    <div class="pull-right">
                        <a class="btn btn-success" href="@Url.Action("ThemGioHang", "Giohang",
                            new { @id = item.MADT, @strUrl = Request.Url.ToString() })">Đặt mua</a>
                    </div>
                    <div class="pull-left">
                        @Html.ActionLink("Thông tin", "thong_tin", "DienThoai", new { id = item.MADT }, new { @class = "btn btn-default" })
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div>
    <div>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) /  @Model.PageCount
    </div>
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("danh_sach", "DienThoai", new
        {
            page = page
        }))
    </div>
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>
<style type="text/css">
    #mau-nut a {
        clear: both;
        background-color: orange;
        color: snow;
    }

        #mau-nut a:hover {
            background-color: darkcyan;
            color: snow;
        }
</style>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function () {
        var maxLength = 100;
        $(".show-read-more").each(function () {
            var myStr = $(this).text();
            if ($.trim(myStr).length > maxLength) {
                var newStr = myStr.substring(0, maxLength);
                var removedStr = myStr.substring(maxLength, $.trim(myStr).length);
                $(this).empty().html(newStr);

                $(this).append(' <a href="javascript:void(0);" class="read-more">đọc tiếp...</a>');

                $(this).append('<span class="more-text">' + removedStr + '</span>');
            }
        });
        $(".read-more").click(function () {
            $(this).siblings(".more-text").contents().unwrap();
            $(this).remove();
        });
    });
</script>
<style>
    .show-read-more .more-text {
        display: none;
    }
</style>

Nhom4_DoAnWeb_CHDT /Views/DienThoai/danh_sach_QT.cshtml
@model PagedList.IPagedList<Nhom4_DoAnWeb_CHDT.Models.tblDIENTHOAI>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Điện thoại - Quản Trị";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Danh Sách điện thoại - Quản Trị</h2>
<p>
    @Html.ActionLink("Thêm điện thoại mới", "them_moi", null, new { @class = "btn btn-warning" })
</p>
<table border="1px">
    <tr>
        <th width="100" style="text-align:center">Mã Điện thoại</th>
        <th width="120" style="text-align:center">Tên Điện thoại</th>
        <th width="80" style="text-align:center">Mã loại</th>
        <th width="200" style="text-align:center">Hình</th>
        <th width="120" style="text-align:center">Giá mua</th>
        <th width="120" style="text-align:center">Giá bán</th>
        <th width="190" style="text-align:center">Mô tả</th>
        <th width="80" style="text-align:center">Số lượng tồn</th>
        <th width="180" style="text-align:center">Danh mục</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align:center">@item.MADT</td>
            <td style="text-align:center">@item.TENDT</td>
            <td style="text-align:center">@item.MALOAI</td>
            <td style="text-align:center">
                <img src="@item.HINH" width="190px" height="190px" />
            </td>
            <td style="text-align:center">@item.GIAMUA</td>
            <td style="text-align:center">@item.GIABAN</td>
            <td style="text-align:center">@item.MOTA</td>
            <td style="text-align:center">@item.SLTON</td>
            <td style="text-align:center; font-size:24px">
                <a href="@Url.Action("sua_thong_tin", new { id = item.MADT })" title="Edit">
                    <img src="~/Content/images/edit-icon.png" alt="Edit" width="22px" />
                </a> |
                <a href="@Url.Action("thong_tin", new { id = item.MADT })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Edit" width="29px" />
                </a> |
                <a href="@Url.Action("xoa_DT", new { id = item.MADT })" title="Delete">
                    <img src="~/Content/images/delete-icon.png" alt="Edit" width="25px" />
                </a>
            </td>
        </tr>
    }
</table>
<style>
    a:hover img {
        position: relative;
        top: -3px;
    }

    img {
        vertical-align: text-bottom;
    }
</style>
<div>
    <div>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) /  @Model.PageCount
    </div>
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("danh_sach_QT", "DienThoai", new
        {
            page = page
        }))
    </div>
</div>
<style>
    .MenuTrang li {
        display: inline;
    }

    #mau-nut a {
        clear: both;
        background-color: orange;
        color: snow;
    }

        #mau-nut a:hover {
            background-color: darkcyan;
            color: snow;
        }
</style>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function () {
        var maxLength = 100;
        $(".show-read-more").each(function () {
            var myStr = $(this).text();
            if ($.trim(myStr).length > maxLength) {
                var newStr = myStr.substring(0, maxLength);
                var removedStr = myStr.substring(maxLength, $.trim(myStr).length);
                $(this).empty().html(newStr);

                $(this).append(' <a href="javascript:void(0);" class="read-more">đọc tiếp...</a>');

                $(this).append('<span class="more-text">' + removedStr + '</span>');
            }
        });
        $(".read-more").click(function () {
            $(this).siblings(".more-text").contents().unwrap();
            $(this).remove();
        });
    });
</script>
<style>
    .show-read-more .more-text {
        display: none;
    }
</style>

Nhom4_DoAnWeb_CHDT /Views/DienThoai/sua_thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblDIENTHOAI

@{
    ViewBag.Title = "Sửa thông tin điện thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin điện thoại</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>tblDIENTHOAI</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MADT)

        <div class="form-group">
            @Html.LabelFor(model => model.TENDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="HINH">
                Hình:
            </label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.HINH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HINH, "", new { @class = "text-danger" })
                <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
                       style="display:none;" />
                <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
                <img src="@Model.HINH"height="400px" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GIAMUA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GIAMUA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GIAMUA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GIABAN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GIABAN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GIABAN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MOTA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MOTA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MOTA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MALOAI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MALOAI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MALOAI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SLTON, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SLTON, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SLTON, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@section upload
{
    <script>
        $(function () {
            $('#btnUpload').click(function () {
                $('#fileUpload').trigger('click');
            });
        });

        $('#fileUpload').change(function () {
            if (window.FormData !== undefined) {
                var fileUpload = $('#fileUpload').get(0);
                var files = fileUpload.files;
                var formData = new FormData();
                formData.append('file', files[0]);

                $.ajax(
                    {
                        type: 'POST',
                        url: '/DienThoai/ProcessUpload',
                        contentType: false,
                        processData: false,
                        data: formData,
                        success: function (urlImage) {

                            $('#pictureUpload').attr('src', urlImage);
                            $('#HINH').val(urlImage);
                        },
                        error: function (err) {
                            alert('Error ', err.statusText);
                        }
                    });
            }
        });
    </script>
}
<div>
    @Html.ActionLink("Quay lại", "danh_sach_QT", "DienThoai")
</div>

Nhom4_DoAnWeb_CHDT /Views/DienThoai/thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblDIENTHOAI

@{
    ViewBag.Title = "Thông tin điện thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin Điện Thoại</h2>

<div>
    <hr />
    <h2 style="text-decoration:underline">
        @Html.DisplayFor(model => model.TENDT)
    </h2>
    <div class="thongtin" style="display:flex">
        <div class="left" style="width:60%">

            <img src="@Model.HINH" width="60%" />
        </div>
        <div class="right" style="width:40%; margin-top: 5%">
            <h4 style="color:orangered; font-size:30px"> @Html.DisplayFor(model => model.GIABAN)</h4>
            <p style="font-size:18px"> @Html.DisplayFor(model => model.MOTA)</p>
            <div class="button" style="display:flex">
                <a class="btn btn-default" style="width:30%;margin-right:20px" href="@Url.Action("trang_chu", "KhoaiTei")">Quay lại</a>

                <a class="btn btn-success" style="width:60%" href="@Url.Action("ThemGioHang", "Giohang",
                                        new { @id = @Model.MADT, @strUrl = Request.Url.ToString() })">Đặt mua</a>
            </div>
        </div>
    </div>
    <br />
    <p style="font-size:16px">
        <span><img src="~/Content/images/uytin.jpg" width="30px"></span>
        Hàng chính hãng - Bảo hành 12 Tháng
        <span><img src="~/Content/images/ship.jpg" width="30px"></span>
        Giao hàng toàn quốc
    </p>
</div>

Nhom4_DoAnWeb_CHDT /Views/DienThoai/tim_kiem.cshtml
@model PagedList.IPagedList<Nhom4_DoAnWeb_CHDT.Models.tblDIENTHOAI>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Tìm kiếm Điện Thoại";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string search = (string)Session["searchDT"];
}
<h2>Danh sách các Điện Thoại bạn cần tìm</h2>
<div class="row">
    @foreach (var item in Model)
    {
        var gia = item.GIABAN.ToString().Replace(",0000", "");
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-default">
                <div class="panel panel-heading">
                    <img src="@item.HINH" alt="hinh thumnail" width="214px" height="214px">
                </div>
                <div class="panel-body">
                    @item.TENDT
                    <p><strong>Giá: </strong>@gia</p>
                    <p><strong>Số lượng tồn: </strong>@item.SLTON</p>
                </div>
                <div class="panel-footer clearfix">
                    <div class="pull-right">
                        <a class="btn btn-success" href="@Url.Action("ThemGioHang", "Giohang",
                            new { @id = item.MADT, @strUrl = Request.Url.ToString() })">Đặt mua</a>
                    </div>
                    <div class="pull-left">
                        @Html.ActionLink("Thông tin", "thong_tin", "DienThoai", new { id = item.MADT }, new { @class = "btn btn-default" })
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div>
    <div>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) /  @Model.PageCount
    </div>
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("tim_kiem", "DienThoai", new
   {
       page = page,
       searchName = search
   }))
    </div>
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>
<style type="text/css">
    #mau-nut a {
        clear: both;
        background-color: orange;
        color: snow;
    }

        #mau-nut a:hover {
            background-color: darkcyan;
            color: snow;
        }
</style>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function () {
        var maxLength = 100;
        $(".show-read-more").each(function () {
            var myStr = $(this).text();
            if ($.trim(myStr).length > maxLength) {
                var newStr = myStr.substring(0, maxLength);
                var removedStr = myStr.substring(maxLength, $.trim(myStr).length);
                $(this).empty().html(newStr);

                $(this).append(' <a href="javascript:void(0);" class="read-more">đọc tiếp...</a>');

                $(this).append('<span class="more-text">' + removedStr + '</span>');
            }
        });
        $(".read-more").click(function () {
            $(this).siblings(".more-text").contents().unwrap();
            $(this).remove();
        });
    });
</script>
<style>
    .show-read-more .more-text {
        display: none;
    }
</style>